### ISSUE TITLE
[Improvement] Server Address ending with / gives "authentication failed"

### ISSUE THREAD

**Issue by xEtarusx** [astubenbord/paperless-mobile#56]
Hello,

I encountered an error when you're on the first screen "Connect to Paperless" where you have to enter the server address, username and password you cannot proceed if the server address ends with a slash /.

Does work: http://subdomain.domain.tld
Doesn't work: http://subdomain.domain.tld/

Maybe this can be fixed. I copy and pasted my URL from somewhere else and that's why it had the slash at the end.

If that's too much work maybe just add a simple notice that it should not end with a slash 😉 

Regards,
Etarus

**Comment by xEtarusx** [comment]
I implemented a fix myself. Not sure if it's the correct place to put the code as I'm new to flutter/dart.

**Comment by astubenbord** [comment]
Hi, sorry for the wait, I implemented it a bit differently because I wanted to validate urls. Could you give me some feedback on whether the newest version (v1.4.0-beta) accomplishes what you asked for?

Cheers!

**Comment by xEtarusx** [comment]
It works fine with the new version. You can enter the server address with or without trailing slash.

One thing I find curious is that the server address validator shows a green checkmark if you put like 5 slashes at the end ("http://subdomain.domain.tld/////") but you still get a authentication failure with 403 status code.

I think that nobody would ever enter such string but I was wondering why it shows the green checkmark. Maybe that could be improved later on.

**Comment by astubenbord** [comment]
Yeah, I see what you mean. Validating and matching all valid internet addresses (including domain names, ipvr and ipv6) is not trivial as there are many edge cases. 
The green checkmark only indicates whether the host is reachable or not, maybe I will implement a healthcheck which ensures that a paperless instance is running on the specified url.
